-- =========================
-- GEOGRAFÍA
-- =========================
DROP SCHEMA IF EXISTS geografia, infraestructura, rrhh, institucional, normativa, vacantes, supervision, relevamiento, programas CASCADE;
create schema if not exists geografia;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

create table geografia.provincia (
    id_provincia int generated by default as identity,
    nombre varchar(50) not null,
    constraint pk_provincia primary key (id_provincia)
);

create table geografia.departamento (
    id_departamento int generated by default as identity,
    nombre varchar(50) not null,
    id_provincia int not null,
    constraint pk_departamento primary key (id_departamento),
    constraint fk_departamento_provincia foreign key (id_provincia) REFERENCES geografia.provincia (id_provincia)
);

create table geografia.localidad (
    id_localidad int generated by default as identity,
    nombre varchar(50) not null,
    id_departamento int not null,
    constraint pk_localidad primary key (id_localidad),
    constraint fk_localidad_departamento foreign key (id_departamento) REFERENCES geografia.departamento (id_departamento)
);

create table geografia.domicilio (
    id_domicilio int generated by default as identity,
    calle varchar(50) not null,
    altura int not null,
    id_localidad int not null,
    constraint pk_domicilio primary key (id_domicilio),
    constraint fk_domicilio_localidad foreign key (id_localidad) references geografia.localidad (id_localidad)
);

-- =========================
-- INFRAESTRUCTURA
-- =========================
create schema if not exists infraestructura;

create table infraestructura.edificio (
    id_edificio int generated by default as identity,
    id_domicilio int not null,
    constraint pk_edificio primary key (id_edificio),
    constraint fk_edificio_domicilio foreign key (id_domicilio) references geografia.domicilio (id_domicilio)
);

create table infraestructura.proveedor (
    id_proveedor int generated by default as identity,
    nombre varchar(50) not null,
    constraint pk_proveedor primary key (id_proveedor),
    constraint uq_proveedor unique (nombre)
);

create table infraestructura.tecnologia (
    id_tecnologia int generated by default as identity,
    descripcion varchar(50) not null, -- wifi, cableado, etc.
    constraint pk_tecnologia primary key (id_tecnologia)
);

create table infraestructura.calidad_servicio (
    id_calidad_servicio int generated by default as identity,
    descripcion varchar(50) not null, -- MALA BUENA MUY MALA ETC.
    constraint pk_calidad_servicio primary key (id_calidad_servicio)
);

create table infraestructura.edificio_conexion (
    id_edificio_conexion int generated by default as identity,
    id_edificio int not null,
    id_proveedor int not null,
    id_tecnologia int not null,
    id_calidad_servicio int not null,
    fecha_relevamiento date default CURRENT_DATE,
    observaciones varchar(200) null,
    constraint pk_edificio_conexion primary key (id_edificio_conexion),
    constraint fk_ec_edificio foreign key (id_edificio) references infraestructura.edificio (id_edificio),
    constraint fk_ec_proveedor foreign key (id_proveedor) references infraestructura.proveedor (id_proveedor),
    constraint fk_ec_tecnologia foreign key (id_tecnologia) references infraestructura.tecnologia (id_tecnologia),
    constraint fk_ec_calidad_servicio foreign key (id_calidad_servicio) references infraestructura.calidad_servicio (id_calidad_servicio)
);

-- =========================
-- RRHH
-- =========================
create schema if not exists rrhh;

create table rrhh.persona (
    id_persona int generated by default as identity,
    dni int not null,
    nombre varchar(50) not null,
    apellido varchar(50) not null,
    telefono varchar(20) not null,
    mail varchar(100) not null,
    constraint pk_persona primary key (id_persona),
    constraint uq_persona_dni unique (dni),
    constraint uq_persona_mail unique (mail),
    constraint ck_persona_dni check (
        dni between 1000000 and 99999999
    )
);

create unique index uq_persona_mail_lower on rrhh.persona (lower(mail));

create table rrhh.rol (
    id_rol int generated by default as identity,
    codigo varchar(20) not null,
    constraint uq_rol_codigo unique (codigo),
    constraint pk_rol primary key (id_rol)
);

-- =========================
-- INSTITUCIONAL
-- =========================
create schema if not exists institucional;

CREATE TABLE institucional.servicio_comida (
    id_serv_comida INT generated by default as identity,
    nombre VARCHAR(50) NOT NULL,
    constraint pk_servicio_comida PRIMARY KEY (id_serv_comida)
);

CREATE TABLE institucional.categoria (
    id_categoria INT NOT NULL,
    codigo INT NOT NULL,
    descripcion VARCHAR(100) NOT NULL,
    constraint pk_categoria PRIMARY KEY (id_categoria),
    constraint uq_categoria_codigo UNIQUE (codigo)
);

CREATE TABLE institucional.zona (
    id_zona INT NOT NULL,
    codigo CHAR(1) NOT NULL,
    descripcion VARCHAR(100) NOT NULL,
    constraint pk_zona PRIMARY KEY (id_zona),
    constraint uq_zona_codigo UNIQUE (codigo)
);

create table institucional.turno (
    id_turno int generated always as identity,
    descripcion varchar(50),
    constraint pk_turno primary key (id_turno)
);

CREATE TABLE institucional.modalidad (
    id_modalidad INT generated by default as identity,
    descripcion VARCHAR(100) NOT NULL,
    constraint pk_modalidad PRIMARY KEY (id_modalidad)
);

CREATE TABLE institucional.escuela (
    cue BIGINT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    fecha_fundacion DATE NULL,
    telefono varchar(20) NOT NULL,
    mail VARCHAR(100) NOT NULL,
    id_escuela INT generated by default as identity,
    cabecera_id INT NULL,
    id_serv_comida INT NOT NULL,
    id_categoria INT NOT NULL,
    id_zona INT NOT NULL,
    id_modalidad INT NOT NULL,
    id_turno INT NOT NULL,
    constraint pk_escuela PRIMARY KEY (id_escuela),
    constraint fk_escuela_cabecera FOREIGN KEY (cabecera_id) REFERENCES institucional.escuela (id_escuela),
    constraint fk_escuela_servicio_comida FOREIGN KEY (id_serv_comida) REFERENCES institucional.servicio_comida (id_serv_comida),
    constraint fk_escuela_categoria FOREIGN KEY (id_categoria) REFERENCES institucional.categoria (id_categoria),
    constraint fk_escuela_zona FOREIGN KEY (id_zona) REFERENCES institucional.zona (id_zona),
    constraint fk_escuela_modalidad FOREIGN KEY (id_modalidad) REFERENCES institucional.modalidad (id_modalidad),
    constraint fk_escuela_turno FOREIGN KEY (id_turno) REFERENCES institucional.turno (id_turno),
    constraint uq_escuela_cue UNIQUE (cue),
    constraint uq_escuela_mail UNIQUE (mail)
);

alter table institucional.escuela
add column anexo char(2) null default '00';

-- =========================
-- NORMATIVA
-- =========================
CREATE SCHEMA IF NOT EXISTS normativa;

CREATE TABLE normativa.disposicion (
    id_disposicion INT GENERATED BY DEFAULT AS IDENTITY,
    numero INT NOT NULL,
    anio INT NOT NULL,
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    titulo VARCHAR(100),
    observaciones VARCHAR(300),
    CONSTRAINT pk_disposicion primary key (id_disposicion),
    CONSTRAINT uq_disposicion_numero_anio UNIQUE (numero, anio)
);

CREATE TABLE normativa.autoridad (
    id_autoridad INT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(50) NOT NULL,
    sigla VARCHAR(5) NOT NULL,
    descripcion VARCHAR(100) NOT NULL,
    CONSTRAINT pk_autoridad primary key (id_autoridad),
    CONSTRAINT uq_autoridad_sigla UNIQUE (sigla),
    CONSTRAINT uq_autoridad_nombre UNIQUE (nombre)
);

-- =========================
-- VACANTES
-- =========================

create schema if not exists vacantes;

-- Catálogo de cargos (prefijo-sufijo)
CREATE TABLE vacantes.cargo (
    id_cargo INT GENERATED BY DEFAULT AS IDENTITY,
    prefijo INT NOT NULL, -- p.ej., 05 (se guarda por escalabilidad)
    sufijo INT NOT NULL, -- p.ej., 328 (se usa para identificar el puesto)
    descripcion VARCHAR(100),
    id_rol INT NOT NULL,
    codigo_display VARCHAR(20) GENERATED ALWAYS AS (
        LPAD(prefijo::TEXT, 2, '0') || '-' || LPAD(sufijo::TEXT, 3, '0')
    ) stored,
    CONSTRAINT uq_cargo_prefijo_sufijo UNIQUE (prefijo, sufijo),
    constraint pk_cargo primary key (id_cargo),
    constraint fk_cargo_rol foreign key (id_rol) references rrhh.rol (id_rol)
);

-- Plazas (físicas) por escuela
CREATE TABLE vacantes.plaza (
    id_plaza INT GENERATED BY DEFAULT AS IDENTITY,
    id_escuela INT NOT NULL,
    prefijo INT NOT NULL,
    sufijo INT NOT NULL,
    codigo_display VARCHAR(20) GENERATED ALWAYS AS (
        LPAD(prefijo::TEXT, 2, '0') || '-' || LPAD(sufijo::TEXT, 3, '0')
    ) stored,
    descripcion VARCHAR(150),
    id_turno INT NOT NULL,
    id_cargo INT NOT NULL,
    constraint fk_plaza_escuela foreign key (id_escuela) references institucional.escuela (id_escuela),
    CONSTRAINT pk_plaza PRIMARY KEY (id_plaza, id_escuela),
    CONSTRAINT fk_plaza_turno FOREIGN KEY (id_turno) REFERENCES institucional.turno (id_turno),
    CONSTRAINT fk_plaza_cargo FOREIGN KEY (id_cargo) REFERENCES vacantes.cargo (id_cargo),
    -- dentro de la escuela, un único código plaza (prefijo-sufijo)
    CONSTRAINT uq_plaza_codigo_por_escuela UNIQUE (id_escuela, prefijo, sufijo)
    -- validaciones básicas
    -- CONSTRAINT chk_plaza_prefijo_pos CHECK (prefijo > 0),
    -- CONSTRAINT chk_plaza_sufijo_pos CHECK (sufijo > 0)
);

-- PK compuesta asegura coherencia por escuela y habilita 1:1 con asignación
CREATE TABLE vacantes.vacante (
    id_vacante INT GENERATED BY DEFAULT AS IDENTITY,
    id_escuela INT NOT NULL,
    id_plaza INT NOT NULL,
    estado VARCHAR(20) NOT NULL, -- 'ABIERTA' | 'RESERVADA' | 'CUBIERTA' | 'CERRADA'
    fecha_vacante DATE NOT NULL DEFAULT CURRENT_DATE,
    motivo VARCHAR(50),
    id_disposicion INT NOT NULL,
    CONSTRAINT pk_vacante PRIMARY KEY (id_vacante, id_escuela),
    CONSTRAINT fk_vacante_plaza_escuela FOREIGN KEY (id_plaza, id_escuela) REFERENCES vacantes.plaza (id_plaza, id_escuela),
    CONSTRAINT fk_vacante_disposicion FOREIGN KEY (id_disposicion) REFERENCES normativa.disposicion (id_disposicion),
    CONSTRAINT chk_vacante_estado CHECK (
        estado IN (
            'ABIERTA',
            'RESERVADA',
            'CUBIERTA',
            'CERRADA'
        )
    )
);

-- Asignación vigente (una por vacante)
CREATE TABLE vacantes.asignacion (
    id_vacante INT NOT NULL,
    id_escuela INT NOT NULL,
    id_persona INT NOT NULL,
    id_autoridad INT NOT NULL,
    id_disposicion INT NOT NULL,
    fecha_asignacion DATE NOT NULL DEFAULT CURRENT_DATE,
    -- La PK es la misma clave de la vacante => 1 vacante = 1 ocupante vigente
    CONSTRAINT pk_asignacion PRIMARY KEY (id_vacante, id_escuela),
    CONSTRAINT fk_asignacion_vacante FOREIGN KEY (id_vacante, id_escuela) REFERENCES vacantes.vacante (id_vacante, id_escuela),
    CONSTRAINT fk_asignacion_autoridad FOREIGN KEY (id_autoridad) REFERENCES normativa.autoridad (id_autoridad),
    CONSTRAINT fk_asignacion_disposicion FOREIGN KEY (id_disposicion) REFERENCES normativa.disposicion (id_disposicion),
    CONSTRAINT fk_asignacion_persona FOREIGN KEY (id_persona) REFERENCES rrhh.persona (id_persona)
);

-- Índices útiles para consultas
CREATE INDEX IF NOT EXISTS ix_plaza_escuela_cargo ON vacantes.plaza (id_escuela, id_cargo);

CREATE INDEX IF NOT EXISTS ix_vacante_estado_escuela ON vacantes.vacante (id_escuela, estado);

CREATE INDEX IF NOT EXISTS ix_asignacion_persona ON vacantes.asignacion (id_persona);

create schema if not exists supervision;

create table supervision.supervisor_escuela (
    id_persona int not null,
    id_cargo int not null,
    id_escuela int not null,
    id_autoridad int not null,
    constraint pk_supervisor_escuela PRIMARY KEY (id_escuela),
    constraint fk_se_escuela foreign key (id_escuela) references institucional.escuela (id_escuela),
    constraint fk_se_persona foreign key (id_persona) references rrhh.persona (id_persona),
    constraint fk_se_cargo foreign key (id_cargo) references vacantes.cargo (id_cargo),
    constraint fk_se_autoridad foreign key (id_autoridad) references normativa.autoridad (id_autoridad)
);

create index idx_se_por_persona on supervision.supervisor_escuela (id_persona);

create schema if not exists relevamiento;

create table relevamiento.matricula (
    id_escuela int not null,
    anio int not null,
    cantidad int not null,
    constraint pk_matricula primary key (id_escuela, anio),
    constraint fk_matricula_escuela foreign key (id_escuela) references institucional.escuela (id_escuela)
);

create table relevamiento.problematica (
    id_problematica int generated by default as identity,
    dimension varchar(50) not null,
    descripcion varchar(50),
    constraint pk_problematica primary key (id_problematica)
);

create table relevamiento.escuela_problematica (
    id_problematica int not null,
    id_escuela int not null,
    constraint pk_escuela_problematica primary key (id_problematica, id_escuela),
    constraint fk_ep_problematica foreign key (id_problematica) references relevamiento.problematica (id_problematica),
    constraint fk_ep_escuela foreign key (id_escuela) references institucional.escuela (id_escuela)
);

create table relevamiento.cocina(
    id_cocina int generated by default as identity,
    id_escuela int not null,
    fecha date not null,
    datos jsonb not null,
    constraint pk_cocina primary key (id_cocina),
    constraint fk_cocina_escuela foreign key (id_escuela) references institucional.escuela (id_escuela)
)

create index idx_cocina_escuela on relevamiento.cocina (id_escuela);


create schema if not exists programas;

create table programas.programa_acompanamiento (
    id_programa int generated by default as identity,
    descripcion varchar(100) not null,
    constraint pk_programa_acompanamiento primary key (id_programa)
);

create table programas.escuela_programa (
    id_programa int not null,
    id_escuela int not null,
    constraint pk_escuela_programa primary key (id_programa, id_escuela),
    constraint fk_ep_programa foreign key (id_programa) references programas.programa_acompanamiento (id_programa),
    constraint fk_ep_escuela foreign key (id_escuela) references institucional.escuela (id_escuela)
);

create schema if not exists staging;

create table staging.escuelas_raw2 (
    id_escuela int generated by default as identity,
    cue varchar(12),
    nombre varchar(150),
    departamento varchar(50),
    categoria char(1),
    zona char(1),
    fecha_fundacion date,
    localidad varchar(150),
    matricula_2025 int,
    matricula_2024 int,
    modalidad varchar(20),
    nombre_director varchar(20),
    situacion_revista varchar(20),
    telefono varchar(20),
    mail varchar(100),
    ambito varchar(30),
    turno varchar(20),
    constraint pk_escuelas_raw2 primary key (id_escuela)
);

drop table staging.escuelas_raw2 cascade;

create table relevamiento.personal_tipo (
    id_personal_tipo int generated by default as identity,
    codigo varchar(20) not null,
    nombre varchar(100) not null,
    id_rol int null,
    activo boolean not null default true,
    constraint uq_personal_tipo_codigo unique (codigo),
    constraint pk_personal_tipo primary key (id_personal_tipo),
    constraint fk_personal_tipo_rol foreign key (id_rol) references rrhh.rol (id_rol)
);

create table relevamiento.personal (
    id_escuela int not null,
    anio int not null,
    id_personal_tipo int not null,
    cantidad int not null,
    observaciones varchar(200),
    constraint pk_personal primary key (
        id_escuela,
        anio,
        id_personal_tipo
    ),
    constraint fk_personal_tipo foreign key (id_personal_tipo) references relevamiento.personal_tipo (id_personal_tipo),
    constraint fk_personal_escuela foreign key (id_escuela) references institucional.escuela (id_escuela),
    constraint ck_personal_cantidad check (cantidad >= 0),
    constraint ck_personal_anio check (anio >= 2000)
);

create index if not exists ix_personal_escuela_anio on relevamiento.personal (id_escuela, anio);

create index if not exists ix_personal_tipo on relevamiento.personal (id_personal_tipo);

create table institucional.ambito_escuela (
    id_ambito int generated by default as identity,
    codigo varchar(20) not null,
    activo boolean not null default true,
    constraint uq_ambito_codigo unique (codigo),
    constraint pk_ambito primary key (id_ambito)
);

insert into
    institucional.ambito_escuela (codigo)
values ('URBANA'),
    ('RURAL');

alter table institucional.escuela add column id_ambito int null;

alter table institucional.escuela
add constraint fk_escuela_ambito foreign key (id_ambito) references institucional.ambito_escuela (id_ambito);

create table institucional.director_escuela (
    id_director_escuela int generated by default as identity,
    id_plaza int not null,
    id_escuela int not null,
    id_persona int not null,
    fecha_inicio DATE not null DEFAULT CURRENT_DATE,
    fecha_fin DATE null,
    constraint pk_director_escuela primary key (id_director_escuela),
    constraint fk_director_persona foreign key (id_persona) references rrhh.persona (id_persona),
    constraint fk_director_plaza_escuela foreign key (id_plaza, id_escuela) references vacantes.plaza (id_plaza, id_escuela)
);

-- create schema if not exists auth;

-- create table auth.usuario (
--     id_usuario int generated by default as identity,
--     username varchar(100) not null,
--     password_hash varchar(200) not null,
--     id_persona int not null,
--     id_rol int not null,
--     activo boolean not null default true,
--     constraint pk_usuario primary key (id_usuario),
--     constraint uq_usuario_username unique (username),
--     constraint fk_usuario_rol foreign key (id_rol) references rrhh.rol (id_rol),
--     constraint fk_usuario_persona foreign key (id_persona) references rrhh.persona (id_persona)
-- );

-- create table auth.usuario_escuela (
--     id_usuario int not null,
--     id_escuela int not null,
--     constraint pk_usuario_escuela primary key (id_usuario, id_escuela),
--     constraint fk_ue_usuario foreign key (id_usuario) references auth.usuario (id_usuario),
--     constraint fk_ue_escuela foreign key (id_escuela) references institucional.escuela (id_escuela)
-- )


create table institucional.planilla_novedades (
    id_planilla bigint generated by default as identity,
    id_escuela int not null,
    mes int not null,
    anio int not null,
    fecha_envio timestamp with time zone not null default current_timestamp,
    usuario_envio text not null,
    datos jsonb not null,
    estado varchar (20) not null default 'ENVIADA',
    constraint uq_planilla_escuela_mes_anio unique (id_escuela, mes, anio),
    constraint fk_planilla_usuario foreign key (usuario_envio) references auth."user" (id),
    constraint pk_planilla_novedades primary key (id_planilla),
    constraint fk_planilla_escuela foreign key (id_escuela) references institucional.escuela (id_escuela)
);


-- alter table institucional.planilla_novedades
-- add COLUMN datos jsonb not null;


-- alter table institucional.planilla_novedades
-- add constraint uq_planilla_escuela_mes_anio unique (id_escuela, mes, anio);

-- =========================
-- TIMESTAMPS AUDIT COLUMNS
-- =========================

-- Añadir timestamps a tablas principales
alter table rrhh.persona
add column created_at timestamp
with
    time zone not null default current_timestamp,
add column updated_at timestamp
with
    time zone not null default current_timestamp;

alter table institucional.escuela
add column created_at timestamp
with
    time zone not null default current_timestamp,
add column updated_at timestamp
with
    time zone not null default current_timestamp;

alter table normativa.disposicion
add column created_at timestamp
with
    time zone not null default current_timestamp,
add column updated_at timestamp
with
    time zone not null default current_timestamp;

alter table vacantes.vacante
add column created_at timestamp
with
    time zone not null default current_timestamp,
add column updated_at timestamp
with
    time zone not null default current_timestamp;

alter table vacantes.asignacion
add column created_at timestamp
with
    time zone not null default current_timestamp,
add column updated_at timestamp
with
    time zone not null default current_timestamp;

alter table infraestructura.edificio_conexion
add column created_at timestamp
with
    time zone not null default current_timestamp,
add column updated_at timestamp
with
    time zone not null default current_timestamp;



    -- Indices en foreign keys


CREATE INDEX idx_escuela_categoria ON institucional.escuela(id_categoria);
CREATE INDEX idx_escuela_zona ON institucional.escuela(id_zona);
CREATE INDEX idx_escuela_modalidad ON institucional.escuela(id_modalidad);
CREATE INDEX idx_escuela_turno ON institucional.escuela(id_turno);
CREATE INDEX idx_escuela_servicio_comida ON institucional.escuela(id_serv_comida);
CREATE INDEX idx_escuela_ambito ON institucional.escuela(id_ambito);
CREATE INDEX idx_escuela_cabecera ON institucional.escuela(cabecera_id);

CREATE INDEX idx_departamento_provincia ON geografia.departamento(id_provincia);
CREATE INDEX idx_localidad_departamento ON geografia.localidad(id_departamento);
CREATE INDEX idx_domicilio_localidad ON geografia.domicilio(id_localidad);
CREATE INDEX idx_edificio_domicilio ON infraestructura.edificio(id_domicilio);

CREATE INDEX idx_plaza_turno ON vacantes.plaza(id_turno);
CREATE INDEX idx_plaza_cargo ON vacantes.plaza(id_cargo);

CREATE INDEX idx_vacante_disposicion ON vacantes.vacante(id_disposicion);
CREATE INDEX idx_asignacion_disposicion ON vacantes.asignacion(id_disposicion);
CREATE INDEX idx_asignacion_autoridad ON vacantes.asignacion(id_autoridad);

CREATE INDEX idx_director_escuela_persona ON institucional.director_escuela(id_persona);
CREATE INDEX idx_director_escuela_plaza ON institucional.director_escuela(id_plaza, id_escuela);

-- CREATE INDEX idx_usuario_persona ON auth.usuario(id_persona);
-- CREATE INDEX idx_usuario_rol ON auth.usuario(id_rol);

CREATE INDEX idx_planilla_usuario ON institucional.planilla_novedades(usuario_envio);

CREATE INDEX idx_matricula_anio ON relevamiento.matricula(anio);
CREATE INDEX idx_personal_anio ON relevamiento.personal(anio);

CREATE INDEX idx_cargo_rol ON vacantes.cargo(id_rol);
CREATE INDEX idx_personal_tipo_rol ON relevamiento.personal_tipo(id_rol);



-- indices en busquedas frecuentes


-- Búsquedas por nombre (text search)
CREATE INDEX idx_escuela_nombre_trgm 
ON institucional.escuela 
USING gin(nombre gin_trgm_ops);  
CREATE INDEX idx_persona_apellido_nombre ON rrhh.persona(apellido, nombre);
CREATE INDEX idx_persona_apellido ON rrhh.persona(apellido);

-- Búsquedas por email (case insensitive ya existe en persona, falta en escuela)
CREATE INDEX idx_escuela_mail_lower ON institucional.escuela(LOWER(mail));

-- Búsquedas por fechas
CREATE INDEX idx_director_fecha_fin ON institucional.director_escuela(fecha_fin)
    WHERE fecha_fin IS NULL; -- Índice parcial para directores activos
CREATE INDEX idx_director_fechas ON institucional.director_escuela(fecha_inicio, fecha_fin);

CREATE INDEX idx_disposicion_fecha ON normativa.disposicion(fecha);
CREATE INDEX idx_disposicion_anio ON normativa.disposicion(anio);

CREATE INDEX idx_planilla_fecha_envio ON institucional.planilla_novedades(fecha_envio);
CREATE INDEX idx_planilla_estado ON institucional.planilla_novedades(estado);
CREATE INDEX idx_planilla_anio_mes ON institucional.planilla_novedades(anio, mes);


-- indices en columnas de estados

-- Estados activos/inactivos
-- CREATE INDEX idx_usuario_activo ON auth.usuario(activo) WHERE activo = true;
CREATE INDEX idx_personal_tipo_activo ON relevamiento.personal_tipo(activo) WHERE activo = true;

-- Estados de vacante
CREATE INDEX idx_vacante_estado ON vacantes.vacante(estado);


-- indices compuestos para busquedas comunas

-- Búsquedas combinadas frecuentes
CREATE INDEX idx_escuela_categoria_zona ON institucional.escuela(id_categoria, id_zona);
CREATE INDEX idx_escuela_modalidad_turno ON institucional.escuela(id_modalidad, id_turno);

-- Planillas por escuela y período
CREATE INDEX idx_planilla_escuela_estado ON institucional.planilla_novedades(id_escuela, estado);

-- Personal por escuela y año
CREATE INDEX idx_personal_escuela_anio_tipo ON relevamiento.personal(id_escuela, anio, id_personal_tipo);

-- Timestamps de auditoría
CREATE INDEX idx_escuela_created_at ON institucional.escuela(created_at);
CREATE INDEX idx_persona_created_at ON rrhh.persona(created_at);
CREATE INDEX idx_vacante_created_at ON vacantes.vacante(created_at);


    --- Roles



-- ==========================================
-- 2. ROLES POR FUNCIONALIDAD
-- ==========================================

-- Director de Escuela: solo su escuela
-- CREATE ROLE director_role NOLOGIN;
-- GRANT app_base_role TO director_role;
-- GRANT SELECT ON ALL TABLES IN SCHEMA institucional TO director_role;
-- GRANT SELECT ON ALL TABLES IN SCHEMA geografia TO director_role;
-- GRANT INSERT, UPDATE ON institucional.planilla_novedades TO director_role;
-- GRANT SELECT ON rrhh.persona TO director_role;

-- Supervisor: múltiples escuelas
CREATE ROLE supervisor_role NOLOGIN;
GRANT app_base_role TO supervisor_role;
GRANT SELECT ON ALL TABLES IN SCHEMA institucional TO supervisor_role;
GRANT SELECT ON ALL TABLES IN SCHEMA relevamiento TO supervisor_role;
GRANT SELECT ON ALL TABLES IN SCHEMA geografia TO supervisor_role;
GRANT SELECT ON vacantes.vacante, vacantes.plaza, vacantes.cargo TO supervisor_role;

-- -- Administrador de RRHH
-- CREATE ROLE rrhh_admin_role NOLOGIN;
-- GRANT app_base_role TO rrhh_admin_role;
-- GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA rrhh TO rrhh_admin_role;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON vacantes.plaza TO rrhh_admin_role;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON vacantes.vacante TO rrhh_admin_role;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON vacantes.asignacion TO rrhh_admin_role;
-- GRANT SELECT ON institucional.escuela TO rrhh_admin_role;

-- Administrador Institucional
-- CREATE ROLE institucional_admin_role NOLOGIN;
-- GRANT app_base_role TO institucional_admin_role;
-- GRANT SELECT, INSERT, UPDATE ON institucional.escuela TO institucional_admin_role;
-- GRANT SELECT, INSERT, UPDATE ON institucional.director_escuela TO institucional_admin_role;
-- GRANT SELECT ON ALL TABLES IN SCHEMA geografia TO institucional_admin_role;
-- GRANT SELECT ON rrhh.persona TO institucional_admin_role;

-- Analista de Datos (solo lectura)
-- CREATE ROLE analista_role NOLOGIN;
-- GRANT app_base_role TO analista_role;
-- GRANT SELECT ON ALL TABLES IN SCHEMA
--     geografia,
--     infraestructura,
--     institucional,
--     relevamiento,
--     vacantes,
--     programas
-- TO analista_role;

-- Administrador del Sistema (casi todo)
-- CREATE ROLE sistema_admin_role NOLOGIN;
-- GRANT app_base_role TO sistema_admin_role;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA
--     geografia,
--     infraestructura,
--     rrhh,
--     institucional,
--     normativa,
--     vacantes,
--     supervision,
--     relevamiento,
--     programas,
--     auth
-- TO sistema_admin_role;



-- Política: directores solo ven su escuela
-- CREATE POLICY director_own_school ON institucional.planilla_novedades
--     FOR ALL
--     TO director_role
--     USING (
--         id_escuela IN (
--             SELECT id_escuela
--             FROM auth.usuario_escuela
--             WHERE id_usuario = current_setting('app.user_id')::int
--         )
--     );

    -- Crear tabla de auditoría de accesos
CREATE SCHEMA IF NOT EXISTS audit;

-- CREATE TABLE audit.login_attempts (
--     id_login_attempt int generated by default as identity,
--     username VARCHAR(100) NOT NULL,
--     ip_address INET,
--     success BOOLEAN NOT NULL,
--     attempt_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     failure_reason VARCHAR(200),
--     constraint pk_login_attempt PRIMARY KEY (id_login_attempt)
-- );

-- CREATE INDEX idx_login_attempts_username ON audit.login_attempts(username);
-- CREATE INDEX idx_login_attempts_time ON audit.login_attempts(attempt_time);
-- CREATE INDEX idx_login_attempts_success ON audit.login_attempts(success);