backend:
  name: github
  repo: geronimoserial/Pagina-CGE
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "noticias"
    label: "Noticias"
    folder: "content/noticias"
    create: true
    identifier_field: "titulo"
    slug: "{{slug}}"
    media_folder: "public/images/noticias"
    public_folder: "/images/noticias"
    fields:
      - { label: "Título", name: "titulo", widget: "string" }
      - { label: "Fecha", name: "fecha", widget: "datetime" }
      - { label: "Resumen", name: "resumen", widget: "string" }
      - { label: "Imagen", name: "imagen", widget: "image" }
      - { label: "Subcategoría", name: "subcategoria", widget: "select", options: ["General", "Educación", "Docentes", "Estudiantes", "Licencias", ""] }
      - { label: "Contenido", name: "body", widget: "markdown" }

  - name: "tramites"
    label: "Trámites"
    folder: "content/tramites"
    create: true
    identifier_field: "titulo"
    slug: "{{slug}}"
    media_folder: "public/images/tramites"
    public_folder: "/images/tramites"
    fields:
      - { label: "Título", name: "titulo", widget: "string" }
      - { label: "Fecha", name: "fecha", widget: "datetime" }
      - { label: "Resumen", name: "resumen", widget: "string" }
      - { label: "Imagen", name: "imagen", widget: "image" }
      - { label: "Subcategoría", name: "subcategoria", widget: "select", options: ["Inscripción", "Certificados", "Títulos"] }
      - { label: "Contenido", name: "body", widget: "markdown" }
