backend:
  name: github
  repo: geronimoserial/documentos-web-cge
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "noticias"
    label: "Noticias"
    folder: "public/content/noticias"
    create: true
    identifier_field: "titulo"
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    public_folder: "/images"
    fields:
      - { label: "Título", name: "titulo", widget: "string" }
      - { label: "Título corto", name: "titulo_corto", widget: "string" }
      - { label: "Fecha", name: "fecha", widget: "datetime" }
      - { label: "Resumen", name: "resumen", widget: "string" }
      - { label: "Imagen", name: "imagen", widget: "image" }
      - {
          label: "Subcategoría",
          name: "subcategoria",
          widget: "select",
          options:
            [
              "General",
              "Educación",
              "Docentes",
              "Estudiantes",
              "Inscripciones",
              "Resoluciones",
            ],
        }
      - { label: "Contenido", name: "body", widget: "markdown" }

  - name: "tramites"
    label: "Trámites"
    folder: "public/content/tramites"
    create: true
    identifier_field: "titulo"
    slug: "{{slug}}"
    public_folder: "/images"
    fields:
      - { label: "Título", name: "titulo", widget: "string" }
      - { label: "Título corto", name: "titulo_corto", widget: "string" }
      - { label: "Fecha", name: "fecha", widget: "datetime" }
      - { label: "Resumen", name: "resumen", widget: "string" }
      - { label: "Imagen", name: "imagen", widget: "image" }
      - {
          label: "Subcategoría",
          name: "subcategoria",
          widget: "select",
          options:
            ["Inscripción", "Certificados", "Títulos", "Licencias", "Otros"],
        }
      - { label: "Contenido", name: "body", widget: "markdown" }
