backend:
  name: github
  repo: geronimoserial/documentos-web-cge
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "noticias"
    label: "Noticias"
    folder: "public/content/noticias"
    create: true
    identifier_field: "titulo"
    slug: "{{year}}-{{month}}-{{day}}_{{titulo_corto}}"
    public_folder: "/images"
    fields:
      - { label: "Título", name: "titulo", widget: "string" }
      - { label: "Título corto", name: "titulo_corto", widget: "string" }
      - { label: "Fecha", name: "fecha", widget: "datetime" }
      - { label: "Resumen", name: "resumen", widget: "string" }
      - { label: "Imagen", name: "imagen", widget: "image" }
      - {
          label: "Mostrar con prioridad?",
          name: "esImportante",
          widget: "boolean",
        }
      - {
          label: "Subcategoría",
          name: "subcategoria",
          widget: "select",
          options:
            [
              "General",
              "Educación",
              "Docentes",
              "Estudiantes",
              "Inscripciones",
              "Resoluciones",
            ],
        }
      - { label: "Contenido", name: "body", widget: "markdown" }
      - label: "Mostrar carrusel de imágenes"
        name: "mostrar_carrusel"
        widget: "boolean"
        required: false
        default: false
      - label: "Carrusel de imágenes (opcional)"
        name: "imagenes_carrusel"
        widget: "list"
        required: false
        fields:
          - { label: "Imagen", name: "imagen", widget: "image" }
          - {
              label: "Título (opcional)",
              name: "titulo",
              widget: "string",
              required: false,
            }
          - {
              label: "Descripción (opcional)",
              name: "descripcion",
              widget: "string",
              required: false,
            }

  - name: "tramites"
    label: "Trámites"
    folder: "public/content/tramites"
    create: true
    identifier_field: "titulo"
    slug: "{{titulo_corto}}"
    public_folder: "/images"
    fields:
      - { label: "Título", name: "titulo", widget: "string" }
      - { label: "Título corto", name: "titulo_corto", widget: "string" }
      - { label: "Fecha", name: "fecha", widget: "datetime" }
      - { label: "Resumen", name: "resumen", widget: "string" }
      - { label: "Imagen", name: "imagen", widget: "image" }
      - {
          label: "Subcategoría",
          name: "subcategoria",
          widget: "select",
          options:
            ["Inscripción", "Certificados", "Títulos", "Licencias", "Otros"],
        }
      - { label: "Contenido", name: "body", widget: "markdown" }
