name: Build and Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.0

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        env:
          NEXT_PUBLIC_API_URL: ${{ env.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_STRAPI_URL: ${{ env.NEXT_PUBLIC_STRAPI_URL }}
        run: npm run build

      - name: Subir artefactos a VPS (temporal)
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

          rsync -az --delete -e "ssh -i private_key -o StrictHostKeyChecking=no" \
            .next public package.json package-lock.json \
            root@31.97.167.26:/Frontend/Pagina-CGE-temp/

      - name: Swap at칩mico y deploy en VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

          ssh -i private_key -o StrictHostKeyChecking=no root@31.97.167.26 << 'EOF'
            set -e

            cd /Frontend/

            echo "Respaldo de versi칩n anterior..."
            rm -rf Pagina-CGE-backup
            mv Pagina-CGE Pagina-CGE-backup || true

            echo "Promoviendo carpeta temporal..."
            mv Pagina-CGE-temp Pagina-CGE

            cd Pagina-CGE
            echo "Instalando dependencias..."
            npm ci --omit=dev

            echo "Reiniciando aplicaci칩n..."
            pm2 restart app || echo "Advertencia: PM2 no est치 corriendo"

            echo "Despliegue completado correctamente."

            # Limpieza final (si todo fue bien)
            rm -rf ../Pagina-CGE-backup
          EOF
