name: Build and Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.0

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        env:
          NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_STRAPI_URL: ${{ vars.NEXT_PUBLIC_STRAPI_URL }}
        run: npm run build

      - name: Subir artefactos directamente al VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

          rsync -az --delete -e "ssh -i private_key -o StrictHostKeyChecking=no" \
            .next public package.json package-lock.json \
            root@31.97.167.26:/root/Frontend/Pagina-CGE/

      - name: Reinstalar dependencias y reiniciar app en VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

          ssh -i private_key -o StrictHostKeyChecking=no root@31.97.167.26 << 'EOF'
            set -e

            cd /root/Frontend/Pagina-CGE

            echo "Deteniendo aplicación..."
            /root/.nvm/versions/node/v22.17.0/bin/pm2 stop app || echo "PM2 no estaba corriendo"

            echo "Instalando dependencias..."
            /root/.nvm/versions/node/v22.17.0/bin/npm i

            echo "Iniciando aplicación con PM2..."
            /root/.nvm/versions/node/v22.17.0/bin/pm2 start frontend || /root/.nvm/versions/node/v22.17.0/bin/pm2 start npm --name "frontend" -- start

            echo "Despliegue directo completado."
          EOF
